name: build

on:
    push:
        branches:
            - '*'
            - '!master'

jobs:
    prepare-and-build-app:
        runs-on: windows-latest
        env:
            DATABASE_HOST: 'localhost'
            DATABASE_USER: 'root'
            DATABASE_PASSWORD: ''
            DATABASE_DB: 'asa_web_servermanager'
            JWT_SECRET_KEY: 'workflowwithascretkey'
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false
            - name: prepare steam cmd
              run: .\prepare.ps1
            - name: run build
              run: |
                  pnpm i
                  pnpm run lint
                  pnpm run build
