name: build

on:
    push:
        branches:
            - '*'
            - '!master'

jobs:
    prepare-and-build-app:
        runs-on: windows-latest
        env:
            DATABASE_HOST: 'localhost'
            DATABASE_USER: 'root'
            DATABASE_PASSWORD: ''
            DATABASE_DB: 'asa_web_servermanager'
            JWT_SECRET_KEY: 'workflowwithascretkey'
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'yarn'
            - name: run lint
              run: |
                  yarn
                  yarn run lint
            - name: run prepare script
              run: .\prepare.ps1
